### ISSUE TITLE
take a look at https://pypi.org/project/plumbum/

### ISSUE THREAD

**Issue by thelittlebug** [kbairak/pipepy#2]
https://pypi.org/project/plumbum/

regards

**Comment by kbairak** [comment]
Thanks!

There are some differences in the interface design. I may be a bit more inclined to preferring mine, but at the very least there are some very good ideas to steal :smile: .

I will look into this with excitement.

**Comment by elkarouh** [comment]
I like the use of square brackets:
`ls["-a"] | grep["-v", r"\.py"] | wc["-l"]`
Maybe in a future release?

**Comment by kbairak** [comment]
This is very easy to do, just a:

```python
def __getitem__(self, index):
    return self(*index)
```

However, despite appearances (:smile:), I don't want to apply syntactic sugar for its own sake. If you look at the commit history, you might find that at some point I had `-ls` instead of `ls.delay()` or `~gzip` instead of `gzip(_text=False)`, but I decided against these because it made the code hard to read and didn't add anything of value. So, I would like square brackets to invoke some functionality that "feels like" accessing _part of_ the command or its output.

For example, you could apply ranges to get a subset of the output's lines. So, `ps('-e')[:5]` would be almost equivalent to `ps('-e') | head('-5')`. But, as this example already demonstrates, you can use the `head` and `tail` commands just for this purpose.

So, I'll wait until I find a good use-case for square brackets before I implement them.
