### ISSUE TITLE
binary mode incompatible with encoding

### ISSUE THREAD

**Issue by elkarouh** [kbairak/pipepy#7]
Hi,
I tried the following code:
```python
from pipepy import gzip
gzip=gzip(_text=False)
gzip < 'deleteme' > 'deleteme.gz'
```

and i get the following traceback

```python
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    gzip < 'deleteme' > 'deleteme.gz'
  File "/Users/elkarouh/opt/anaconda3/lib/python3.8/site-packages/pipepy/pipepy.py", line 484, in __lt__
    with open(filename, mode, encoding=self._encoding) as f:
ValueError: binary mode doesn't take an encoding argument
```

**Comment by elkarouh** [comment]
Hi again,
I made a quick hack to fix the issue, but then i encountered another issue.
The file 'deleteme.gz' doesn't get created.
It works when i run as a shell command
```shell
gzip < deleteme > deleteme.gz
```
Shoudl i file another issue?

**Comment by elkarouh** [comment]
Hi again,

I tried to fix the second issue by adding parentheses in the test code:
```python
(gzip < 'deleteme') > 'deleteme.gz'
```
It then triggered the same bug as above but in another place, some lines before.
I fixed the lines and it finally worked.
Regards

**Comment by kbairak** [comment]
Hey @elkarouh ,

First bug report! I'm so excited!

I [fixed it](https://github.com/kbairak/pipepy/commit/60ac78b61137a070802c50135d22cf72d6c70a13) and uploaded a new release to PyPI. 

Thank you so much for raising this.

**Comment by elkarouh** [comment]
Hi, 
Thank you for solving the issue.
Still the ```gzip < 'deleteme' > 'deleteme.gz'``` produces no output.
I need to use the parentheses
```(gzip < 'deleteme') > 'deleteme.gz' ```
I am puzzled because '<' and '>' have the same precedence and parentheses ought to be useless.
Any idea?

**Comment by kbairak** [comment]
The parentheses can't be helped unfortunately. At least I can't think of a way to avoid them. I figured out what the problem is while debugging your issue.

When you write:

```python
a < b > c
```

in python, the interpreter silently converts it to:

```python
a < b and b > c
```

So, when you do:

```python
gzip < 'deleteme' > 'deleteme.gz'
```

it will do:

```python
gzip.__lt__('deleteme').__bool__() and 'deleteme' > 'deleteme.gz'
``` 

In the end, if `gzip` returns non-zero you will get `False`, otherwise you will get whatever `'deleteme' > 'deleteme.gz'` returns and the output redirection will not have happened.

I didn't know about this beforehand, so thank you for bringing it to my attention. Thanks to you, I included this issue in the README.
