### ISSUE TITLE
Debug print statements do not work

### ISSUE THREAD

**Issue by elkarouh** [kbairak/pipepy#8]
Hi,
The debug print statement does not work:

```python
>>> from pipepy import date
>>> mydate=date()
>>> print(f"mydate={mydate}")
mydate=Wed Mar 17 22:22:36 CET 2021

>>> print(f"{mydate=}")
mydate=PipePy('date', _returncode=0, _stdout='Wed Mar 17 2...36 CET 2021\n')
```

**Comment by kbairak** [comment]
Hey, thanks for the feedback.

Hmm, I didn't know about this formatting rule. What you are getting is the result of `__repr__`. I haven't documented `__repr__` in the README because it wouldn't be useful for scripting. However, I would argue it is more useful for debugging than the result of `__str__`, so what you show looks more like a feature than a bug.

For example, say you wanted to check which options you have passed into the command *before* evaluating it. If your debug statement actually evaluated the command, it would change the behavior of your script:

```python
from pipepy import aaa
command = aaa.bbb(ccc="ddd")
print(f"{command=}")
# <<< command=PipePy('aaa', 'bbb', '--ccc=ddd')
result = command('eee')()
print(f"{result=}")
# <<< result=PipePy('aaa', 'bbb', '--ccc=ddd', 'eee', _returncode=0, _stdout='blah blah blah')
```

The first `print` statement doesn't trigger an evaluation, which is probably what you want.

_BTW, in order to understand the `f"{a=}"`, I ran the following snippet:_

```python
class Foo:
    def __str__(self):
        return "str"

    def __repr__(self):
        return "repr"

foo = Foo()

print(f"{foo}")
# <<< str
print(f"{foo!r}")
# <<< repr
print(f"{foo=}")
# <<< foo=repr
print(f"{foo=!s}")
# <<< foo=str
print(f"{foo=!r}")
# <<< foo=repr
```

**Comment by elkarouh** [comment]
This came as a surprise to me but when i think about it, you're right; a debug feature shouldn't have any side-effect. This issue may be closed.
